apiVersion: v1
kind: Service
metadata:
  labels:
    app: asana-adapter
  name: asana-adapter
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  - port: 15020
    protocol: TCP
    name: monitoring
    targetPort: 15020    
  selector:
    app: asana-adapter
